### ISSUE TITLE
Need BMC_FRU_ID attribute to put PNOR version information in correct FRU_ID

### ISSUE THREAD

**Issue by wghoffa** [open-power/firestone-xml#12]
I think this needs to be added to the XML file so HB FW will update the correct FRU_ID with the PNOR versioning information-

```
    <attribute>
            <id>BMC_FRU_ID</id>
            <default>43</default>
    </attribute>
```

in this target instance:
<targetInstance>
        <id>sys-0</id>
        <type>sys-sys-power8</type>
        <library_target>false</library_target>
        <instance_name>sys</instance_name>

Though I'm not 100% sure if 43 is the correct #, that is the example from Habanero I believe.

**Comment by williamspatrick** [comment]
Is this still relevant?

**Comment by wghoffa** [comment]
I believe Sertac added this, so not relevant any longer.
