### ISSUE TITLE
'rpt' file has 'Err' for a number of entries of thermal sensors. 

### ISSUE THREAD

**Issue by alvintpwang** [open-power/firestone-xml#19]
# firestone.prt file 

...
CPU1_Temp | CPU1 | 0x03 | 0x01 | <b>Err</b> | 1 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc
CPU1_Func | CPU1 | 0x03 | 0x07 | <b>Err</b> | 1 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc
CORE12_Temp | CORE12 | 0xD0 | 0x01 | <b>Err</b> | 12 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-1/core-0
CORE12_Func | CORE12 | 0xD0 | 0x07 | <b>Err</b> | 12 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-1/core-0
CORE19_Temp | CORE19 | 0xD0 | 0x01 | <b>Err</b> | 19 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-10/core-0
CORE19_Func | CORE19 | 0xD0 | 0x07 | <b>Err</b> | 19 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-10/core-0
CORE20_Temp | CORE20 | 0xD0 | 0x01 | <b>Err</b> | 20 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-11/core-0
CORE20_Func | CORE20 | 0xD0 | 0x07 | <b>Err</b> | 20 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-11/core-0
CORE21_Temp | CORE21 | 0xD0 | 0x01 | <b>Err</b> | 21 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-12/core-0
CORE21_Func | CORE21 | 0xD0 | 0x07 | <b>Err</b> | 21 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-12/core-0
CORE22_Temp | CORE22 | 0xD0 | 0x01 | <b>Err</b> | 22 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-13/core-0
CORE22_Func | CORE22 | 0xD0 | 0x07 | <b>Err</b> | 22 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-13/core-0
CORE23_Temp | CORE23 | 0xD0 | 0x01 | <b>Err</b> | 23 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-14/core-0
CORE23_Func | CORE23 | 0xD0 | 0x07 | <b>Err</b> | 23 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-14/core-0
CORE13_Temp | CORE13 | 0xD0 | 0x01 | <b>Err</b> | 13 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-2/core-0
CORE13_Func | CORE13 | 0xD0 | 0x07 | <b>Err</b> | 13 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-2/core-0
CORE14_Temp | CORE14 | 0xD0 | 0x01 | <b>Err</b> | 14 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-3/core-0
CORE14_Func | CORE14 | 0xD0 | 0x07 | <b>Err</b> | 14 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-3/core-0
CORE15_Temp | CORE15 | 0xD0 | 0x01 | <b>Err</b> | 15 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-4/core-0
CORE15_Func | CORE15 | 0xD0 | 0x07 | <b>Err</b> | 15 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-4/core-0
CORE16_Temp | CORE16 | 0xD0 | 0x01 | <b>Err</b> | 16 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-5/core-0
CORE16_Func | CORE16 | 0xD0 | 0x07 | <b>Err</b> | 16 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-5/core-0
CORE17_Temp | CORE17 | 0xD0 | 0x01 | <b>Err</b> | 17 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-6/core-0
CORE17_Func | CORE17 | 0xD0 | 0x07 | <b>Err</b> | 17 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-6/core-0
CORE18_Temp | CORE18 | 0xD0 | 0x01 | <b>Err</b> | 18 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-9/core-0
CORE18_Func | CORE18 | 0xD0 | 0x07 | <b>Err</b> | 18 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/ex-9/core-0
OCC1_OCC_Active_Sensor | OCC1 | 0xD2 | 0x07 | <b>Err</b> | 1 | 0 | /sys-0/node-0/ponderosa-0/proc_socket-1/module-1/proc/occ-0

**Comment by williamspatrick** [comment]
@Erich-Hauptli - I'm not sure if this is an MRW processing issue or a Firestone XML issue or a Serverwiz issue.  Can you investigate?

**Comment by alvintpwang** [comment]
It seems that we need to create the prt file manually. I use this procedure to create the prt file. FYI.

// Get firestone-xml and srverwiz
cd ~
git clone https://github.com/open-power/serverwiz.git
git clone https://github.com/open-power/firestone-xml.git

// Install perl module
sudo perl -MCPAN -e 'install XML::Simple'

// Create the rpt file
perl -I ~/serverwiz/scripts/ ~/serverwiz/scripts/processMrw.pl -x ~/firestone-xml/firestone.xml -f -r

**Comment by williamspatrick** [comment]
#20 seems to fix this.  I suspect someone had previously updated the XML without updating the report, or maybe there is a bug in the report tool that failed on whatever machine they added it on.  Looks to be fixed now.
