### ISSUE TITLE
Confirm MRW_ENHANCED_GROUPING_NO_MIRRORING is set correctly.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/firestone-xml#32]
See open-power/op-build#493 .

**Comment by ghost** [comment]
This is gating our op-build v1.10 release and has caused it to be delayed (so far) 5 weeks. Please review and merge ASAP. (be that by @bwmashak ,  @Erich-Hauptli or @austinwrx )

**Comment by bwmashak** [comment]
Sertac owns Firestone xml.

**Comment by austinwrx** [comment]
Made the change today.
